Feature/auth
vitali-kruchkou/Innowise-Lab-Internship-Level-1-Google-Speech pull request #1
Opened 2021-04-09 11:01 UTC by vitali-kruchkou

2021-04-11 18:52 UTC, M-fil requested changes
Виталя, все сделано очень круто как для стажера. У меня были идентичные ошибки, как у тебя, когда я был на стажировке в Innowise. Если пофиксишь все эти замечания, то твой скил увеличится на 100%.

Поэтому, Виталя, все в твоих руках. Желаю удачи в исправлении ошибок :)

2021-04-11 18:52 UTC, M-fil commented on src/firebase/firebaseAuthQueries.js
> +  toast.success('Please check your email!');
Смотри, рекомендую сразу подключить react-i18next для переводов использовать функционал этой библиотеки для любога текста, который видит пользователь на экране.

На проектах намного проще, когда весь текст хранится в одном файле (в react-i18next будет json файл). Просто если ты захочешь изменить этот текст 'Please check your email!', то тебе придется его искать по проекту, а так все будет в одном файле

2021-04-11 18:52 UTC, M-fil commented on src/firebase/firebaseAuthQueries.js
> +export const SignOut = async () => {
Придерживайся одного стиля нейминга. Если все называешь с маленькой буквы, то пусть и остальные функции будут с маленькой

2021-04-11 18:52 UTC, M-fil commented on src/firebase/firebaseConfig.js
> +const config = {
Я честно не знаю, зачем ты создал отдельный файл с обращением к process.env. Все ведь можно было сделать в одном файле :)
Не забудь заюзать enum

2021-04-11 18:52 UTC, M-fil commented on src/firebase/index.js
> +// const database = firebaseApp.database();
Комменты удаляем)

2021-04-11 18:52 UTC, M-fil commented on src/firebase/index.js
> +export const generateUserDocument = async (user, additionalData) => {
Эта функция - идеальный пример, который должен быть сагой)

2021-04-11 18:52 UTC, M-fil commented on src/firebase/index.js
> +const getUserDocument = async uid => {
Вообще старайся создавать саги для функций, в которых есть минимум 2 асинхронных запроса, сохранения в чего-то в стор и т.д.

2021-04-11 18:52 UTC, M-fil commented on src/index.tsx
> +import store from './store/toolkit/store';
Я видел, что ты установил redux-thunk. В описании проекта написано, что нужно юзать redux-saga

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/Authentication.jsx
> +      <Route path="/signIn" component={SignIn} />
Я рекомендую создать enum для всех путей. Потому что если тебе нужно будет их заюзать в другом файле, то большая вероятность, что ты допустишь ошибку в правописании путя и все паломается

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/PasswordReset.jsx
> +import React, { useState } from 'react';
Да, насчет компонетов для Authentication. Я рекомендую создать папку components внутри Authentication и пихать туда PasswordReset, SignIn и тд. Делай так для всех модулей

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/PasswordReset.jsx
> +import { resetPassw } from '@store/toolkit/authSlice';
И да, насчет redux toolkit. Лучше делай через обычный redux и redux saga. Так будет правильней и рациональней, я считаю. Redux toolkit добавляет большую зависимость. Он весит больше 1.5 мб

<img width="564" alt="Screenshot 2021-04-11 at 9 17 37 PM" src="https://user-images.githubusercontent.com/56369004/114316290-91eb6200-9b0b-11eb-9632-a35bfd88ba8e.png">

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/PasswordReset.jsx
> +  const sendResetEmail = async event => {
Смотри, сейчас расскажу про очень интересную тему. У меня была такая же "ошибка" в самом начале, как у тебя.

Начни использовать для всех функций компонента useCallback, для сложных вычислений - useMemo. Почитай про эти хуки. Они ОЧЕНЬ важны.

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/PasswordReset.jsx
> +              placeholder="Input your email"
Такой текст стоит располагать в json файле от react-i18next. Сделай то же самое для других таких же примеров. Больше не буду упоминать эту ошибку

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/StyledPasswordReset.js
> +    // max-width: 750px;
Комменты удаляем. Опять же, исправь это везде. Не буду еще раз упоминать эту ошибку

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/StyledPasswordReset.js
> +      background: rgb(151, 11, 221);
Смотри, для любых цветов советую создавать локально enum Colors и пихать туда все цвета, которые используются в файле. Так тебе будет намного легче изменить какой-либо цвет. А так тебе придется его искать по всему файлу.

Запомни и исправь везде. 
```
Любой цвет стоит делать константой
```

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/StyledPasswordReset.js
> +    box-shadow: inset 0 0 0 1px #337ab7;
Для теней тоже советую делать константы

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/PasswordReset/StyledPasswordReset.js
> +    @media (max-width: 768px) {
Для разрешений media запросов (768px) тоже рекомендую делать константы в отдельном файле

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/SignIn/SignIn.jsx
> +  signError,
В этом файле ошибки идентичные как и в ResetPassword

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/SignUp/SignUp.jsx
> +    if (name === 'userEmail') {
'userEmail' стоит делать константой. Есть вероятность, что ты ошибешься в написании и возникнет баг

2021-04-11 18:52 UTC, M-fil commented on src/routes/Routes.jsx
> +      const user = await generateUserDocument(userAuth);
Здесь стоит заюзать сагу, потому что используется один асинхронный запрос и ты диспатчишь что-то в стор. Очень много действий для локальной функции

2021-04-11 18:52 UTC, M-fil commented on src/routes/Routes.jsx
> +  return login ? (
Такая реализация с разделением роутов работает хорошо. Это в принципе правильное решение. Есть также еще один вариант, как можно сделать разделение роутов: https://medium.com/@tomlarge/private-routes-with-react-router-dom-28e9f40c7146

2021-04-11 18:52 UTC, M-fil commented on src/store/actions/authActions.ts
> +const signIn = (user: User | null): AuthActions => {
Рекомендую создавать нейминги для action-ов с приставкой Action в коце. Просто у тебя много раз повторяется signIn в других файлах

2021-04-11 18:52 UTC, M-fil commented on src/store/actions/authActions.ts
> +  return (dispatch: AppDispatch) => {
Опять же, прочитай еще раз внимательно описание проекта. Там указана, что нужно использовать redux-saga, а не redux-thunk

2021-04-11 18:52 UTC, M-fil commented on src/store/actions/constans.d.ts
> +export const SIGN_IN = 'SIGN_IN';
Рекомендую создавать action-types с помощью enum

2021-04-11 18:52 UTC, M-fil commented on src/store/reducers/currentAuth.ts
> +  user: null as any,
В TS нужно удалять все any. Это плохая практика

2021-04-11 18:52 UTC, M-fil commented on src/store/toolkit/authSlice.ts
> +      if (user !== undefined) {
Опять же, у тебя много функций, которые можно оптимизировать с помощью redux-saga. Я еще раз упоминать про это не буду, попробуй это исправить :)

2021-04-11 18:52 UTC, M-fil commented on src/store/toolkit/authSlice.ts
> +    await resetPassword(email).then(() => {
Ты же юзаешь здесь async await. Зачем тебе здесь then?)

2021-04-11 18:52 UTC, M-fil commented on src/type/types.d.ts
> +  | {
Вау, я бы сделал по-другому. Рекомендую создать интерфейсы для всех этих объектов:
```
{
      type: typeof SIGN_UP;
      payload: User | null;
    }
```

2021-04-11 18:52 UTC, M-fil commented on storage.rules
> +service firebase.storage {
Опять же, все правила прописываются в самом Firebase

<img width="1440" alt="Screenshot 2021-04-11 at 9 39 02 PM" src="https://user-images.githubusercontent.com/56369004/114316936-674ed880-9b0e-11eb-936d-38054d2b5c2d.png">

2021-04-11 18:52 UTC, M-fil commented on tsconfig.paths.json
> +      "@modules/*": ["modules/*"],
С путями круто сделал. Респект :)

2021-04-11 18:52 UTC, M-fil commented on src/store/toolkit/authSlice.ts
> +const initialState = {
Смотри, для каждого файла с редьюсером у тебя должен быть interface State, который будет описывать типы и ключи для объекта со стейтом

2021-04-11 18:52 UTC, M-fil commented on src/store/index.ts
> +const store = createStore(rootReducer, applyMiddleware(thunk));
А ты не используешь redux devtools? Нужно подключить, важная штука

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/SignUp/StyledSignUp.js
> +import styled from 'styled-components';
Ошибки идентичные, создаем константы для цветов, box-shadow, border, etc.

2021-04-11 18:52 UTC, M-fil commented on src/modules/Authentication/SignIn/StyledSignIn.js
> +import styled from 'styled-components';
Ошибки идентичные, создаем константы для цветов, box-shadow, border, etc. Убираем комменты

2021-04-11 18:52 UTC, M-fil commented on src/firebase/firebaseAuthQueries.js
> +  toast.success('Please check your email!');
То есть, если текст виден пользоветелю на экране, то его стоит заносить в json файл и затем получать с помощью  useTranslation у react-i18next

2021-04-11 19:41 UTC, vitali-kruchkou commented on firestore.rules
> +service cloud.firestore {
Файл firestore.rules сам создается при выполнении команды npm firestore init

2021-04-20 06:15 UTC, M-fil requested changes
Знаешь, Виталя, ты красавчик! Заюзал redux-saga, разобрался с useCallback, добавил переводы для react-i18next. Машина!

Осталось совсем чуть-чуть до идеала. Идеал - это исправление ошибок, которые я упомянул здесь :)

2021-04-20 06:15 UTC, M-fil commented on src/core/firebase/firebaseConfig.ts
> +const config = {
При запуске npm run lint у меня выбивает ошибка:
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration

Нужно это пофиксить и также исправить все ошибки eslint

2021-04-20 06:15 UTC, M-fil commented on src/core/store/sagas/auth.ts
> +      yield put({
В put лучше передавать функцию, которая возвращает action. Например такие функции, которые у тебя хранятся в authActions

2021-04-20 06:15 UTC, M-fil commented on src/core/store/sagas/auth.ts
> +  yield takeLatest(ActionTypes.ASYNC_SIGN_IN, workerAuthSignIn);
Все действия с этими takeLatest нужно объединить в одну сагу. И запомни правило: 1 файл - 1 сага (1 воркер сага и 1 главная сага с takeEvery либо takeLatest)

2021-04-20 06:15 UTC, M-fil commented on src/core/store/sagas/auth.ts
> +  yield takeLatest(ActionTypes.ASYNC_SIGN_IN, workerAuthSignIn);
Посмотри на этот пример. Так должна выглядеть типичная сага:
```
import { put, call, takeEvery } from 'redux-saga/effects';

import {
  signUpUser,
  signInUser,
  createNewUserTypeInDB,
  uploadImageToStorage,
  getAvatarURL,
  getImageBLOB,
} from '../../service/service';
import {
  fetchUserLoading,
  fetchUserError,
  fetchUserSuccess,
} from '../../redux/user/actions';
import userActionTypes from '../../redux/user/actionTypes';
import { Action, UserObject } from '../../interfaces/interfaces';
import app from '../../firebase';
import { images } from '../../constants/constants';

const { NO_USER_IMAGE } = images;

function* userWorkerSignSaga(action: Action) {
  try {
    const { payload } = action;
    const blob = yield call(getImageBLOB, NO_USER_IMAGE);
    const file = payload.file || blob;

    yield put(fetchUserLoading());
    const { login, password } = payload.user as UserObject;
    yield call(payload.isRegistration ? signUpUser : signInUser, login, password);
    const user = app.auth().currentUser;
    if (user && payload.isRegistration) {
      yield call(uploadImageToStorage, file);
      const avatarURL = yield call(getAvatarURL, payload.userId);
      yield call(createNewUserTypeInDB, payload.user, user?.uid || '', avatarURL);
    }
    yield put(fetchUserSuccess(user));
  } catch (error) {
    yield put(fetchUserError(error.message));
  }
}

function* completeAuthSaga() {
  yield takeEvery(userActionTypes.COMPLETE_USER_AUTH, userWorkerSignSaga);
}

export default completeAuthSaga;
```

2021-04-20 06:15 UTC, M-fil commented on src/modules/Authentication/components/PasswordReset/PasswordReset.tsx
> +    dispatch({
Для любых диспатчей в стор используй action функции, как в authActions.ts

2021-04-20 06:15 UTC, M-fil commented on src/modules/Authentication/components/PasswordReset/StyledPasswordReset.js
>  import styled from 'styled-components';
У этого файла должно быть расширение ts, а не js

2021-04-20 06:15 UTC, M-fil commented on src/modules/Authentication/components/PasswordReset/StyledPasswordReset.js
>  import styled from 'styled-components';
Все файлы в typescript - это либо .tsx, либо .ts

2021-04-20 06:15 UTC, M-fil commented on src/modules/Authentication/components/SignIn/SignIn.tsx
>                <br />
Не будь злодеем)) <br /> - очень плохая практика. Лучше ставить отступы через стили. На реальном проекте тебе бы очень сильно за это напихали)

2021-04-20 06:15 UTC, M-fil commented on src/modules/Home/Home.tsx
> +  const signOut = () => {
Любую функцию внути компонента оборачивай в useCallback

2021-04-20 06:15 UTC, M-fil commented on src/modules/Home/Home.tsx
> +      <h1>Home</h1>
Ну и переводы нужно добавить для текста

2021-04-20 15:28 UTC, M-fil approved these changes

2021-04-21 08:30 UTC, merged